name       : haskell-parsec
version    : 3.1.11
release    : 4
source     :
    - http://hackage.haskell.org/package/parsec-3.1.11/parsec-3.1.11.tar.gz : 6f87251cb1d11505e621274dec15972de924a9074f07f7430a18892064c2676e
license    : BSD-3-Clause
component  : programming.haskell
summary    : Parsec is designed from scratch as an industrial-strength parser library.
description: |
    Parsec is designed from scratch as an industrial-strength parser library.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-mtl
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
