name       : haskell-parsec
version    : 3.1.11
release    : 1
source     :
    - http://hackage.haskell.org/package/parsec-3.1.11/parsec-3.1.11.tar.gz : 6f87251cb1d11505e621274dec15972de924a9074f07f7430a18892064c2676e
license    : BSD-3-Clause
component  : programming
summary    : Parsec is designed from scratch as an industrial-strength parser library.
description: |
    Parsec is designed from scratch as an industrial-strength parser library.
builddeps  :
    - ghc
    - haskell-mtl
    - haskell-text
setup      : |
    sudo ghc-pkg recache
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 parsec-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/parsec-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/parsec-$version/*.a
