name       : haskell-parsec
version    : 3.1.13.0
release    : 5
source     :
    - https://hackage.haskell.org/package/parsec-3.1.13.0/parsec-3.1.13.0.tar.gz : 7861ae437a6177ee7c08899432fd8c062e7c110361da48a9f9e88263fd4d80f1
license    : BSD-3-Clause
component  : programming.haskell
summary    : Parsec is designed from scratch as an industrial-strength parser library.
description: |
    Parsec is designed from scratch as an industrial-strength parser library.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-mtl
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
